// src/StationLinks.vue
<script setup lang="ts">
import { useWindowSize } from "@vueuse/core";
import { computed } from "vue";

const props = defineProps<{
  feature: Geo.Feature;
}>();
const { width } = useWindowSize();

const latitude = computed<number>(() => props.feature.geometry.coordinates[1]);
const longitude = computed<number>(() => props.feature.geometry.coordinates[0]);
const geo = computed<string>(() => `geo:${latitude.value},${longitude.value}`);
const osm = computed<string>(
  () =>
    `https://www.openstreetmap.org/?mlat=${latitude.value}&mlon=${longitude.value}`,
);
const plots = computed<{ interval: string; url: string }[]>(() =>
  "1d/tag 3d/dreitage 1w/woche 1m/monat 6m/winter".split(" ").map((i) => {
    const [interval, fragment] = i.split("/");
    const width0 = width.value < 800 ? 540 : width.value < 1100 ? 800 : 1100;
    const url = `https://wiski.tirol.gv.at/lawine/grafiken/${width0}/standard/${fragment}/${props.feature.properties.plot}.png`;
    return { interval, url };
  }),
);
</script>

<style scoped>
ul,
li {
  padding: 0;
  display: inline;
}
li {
  list-style: none;
}
ul::before {
  content: "[ ";
}
ul::after {
  content: " ]";
}
</style>

<template>
  <ul>
    <li v-for="plot in plots" :key="plot.interval">
      <a :href="plot.url">{{ plot.interval }}</a>
      {{ " " }}
    </li>
    <li>
      <a :href="geo">geo:</a>
      {{ " " }}
    </li>
    <li>
      <a :href="osm" title="Show on OpenStreetMap">osm</a>
    </li>
  </ul>
</template>

// src/StationLinks.svelte
<script>
  export let feature;
  let innerWidth;
  $: latitude = feature.geometry.coordinates[1];
  $: longitude = feature.geometry.coordinates[0];
  $: geo = `geo:${latitude},${longitude}`;
  $: osm = `https://www.openstreetmap.org/?mlat=${latitude}&mlon=${longitude}`;
  $: plots = "1d/tag 3d/dreitage 1w/woche 1m/monat 6m/winter"
    .split(" ")
    .map(i => {
      const [interval, fragment] = i.split("/");
      const width = innerWidth < 800 ? 540 : innerWidth < 1100 ? 800 : 1100;
      const url = `https://wiski.tirol.gv.at/lawine/grafiken/${width}/standard/${fragment}/${feature.properties.plot}.png`;
      return { interval, url };
    });
</script>

<style>
  ul,
  li {
    padding: 0;
    display: inline;
  }
  li {
    list-style: none;
  }
  ul::before {
    content: "[ ";
  }
  ul::after {
    content: " ]";
  }
</style>

<svelte:window bind:innerWidth />
<ul>
  {#each plots as plot (plot.interval)}
    <li>
      <a href={plot.url}>{plot.interval}</a>
      {" "}
    </li>
  {/each}
  <li>
    <a href={geo}>geo:</a>
    {" "}
  </li>
  <li>
    <a href={osm} title="Show on OpenStreetMap">osm</a>
  </li>
</ul>
